### ISSUE TITLE
Updating scisssors 

### ISSUE THREAD

**Issue by cboulanger** [tcr/scissors#15]
Hi everyone, in particular @theapsgroup, @blendlabs, @dennisschaaf, @joe1chen, @abhisekpaul, @toreym, @protocolfirst, @justsml, @steerapi

@tcr, who is not maintaining scissors actively any more, has been so kind as to allow me to update the code. I see that the community has been busy forking and improving and I would like to integrate as much as possible of what you have been doing. The network graph is quite impressive and also quite confusing, so it will take me a bit to figure out who has the latest version with most of the changes. In order to do that, I would like to ask those of you who haven't already to open a pull request with your changes. I'll try to sort it out. 

I will also add JSDoc-style documentation and a Mocha test suite, so we can test that nothing breaks when updating.  A feature I need and will be adding is proper (native) Promise support, without forcing a particular Promise library on module consumers. 

I think scissors is a very useful project for many people - it sure is for me - and I am looking forward to improving it together.

**Comment by tcr** [comment]
I apologize to everyone who contributed and didn't get an answer—@cboulanger is that answer! Thanks again for taking on the task.

**Comment by cboulanger** [comment]
Tim, you're very welcome. There is one thing I would like to ask you, if you can spare 10 minutes: can you look at my JSDoc comments and tell me where they are totally off the mark? I tried to understand the arguments and the code mechanics as best as I could, but I might have gotten something wrong. That would be awesome.

**Comment by tcr** [comment]
@cboulanger All the JSDoc comments look pretty correct. As for `Command`:

* `input` argument should be either a filename (string) or a pipe. If it's a pipe, `this.stream` is set to that value, otherwise null.
* `_input` will return what the command line expects to receive that input argument, either the filename or `-` (i.e. stdin)
* In `_exec`, `this.stream` is either a pipe or null. If it's a pipe, it's piped into the object as stdin. And `_input` is used as the input argument to the command, either the filename or `-` to mean stdin.

I think this allowed for a user to use either a filename or a pipe as input, and to allow piping in the rest of the commands. There used to be one case where content needed to be written to a temporary file and read out again, and this abstraction might have allowed the subsequent command to take the raw filename instead of a Node pipe (since it was pointless to make Node consume the file first).

**Comment by tcr** [comment]
In addition, feel free to bifurcate Command into InputCommand and PipeCommand, or anything more radical. I'm unsure how well this code meshes with modern Node practices.

**Comment by cboulanger** [comment]
We have 19 tests now, which check the generated pdf in more or less depth (some just check that a file has been generated).

**Comment by cboulanger** [comment]
v0.2.0 has been released: https://github.com/tcr/scissors/releases/tag/v0.2.0

Closing this issue.
